apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /usr/local/bin/kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: lb
  name: lb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: lb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /usr/local/bin/kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: lb
    spec:
      containers:
        - args:
            - nginx-debug
            - -g
            - daemon off;
          image: nginx:alpine
          name: lb
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/default.conf
              name: lb-claim0
      restartPolicy: Always
      volumes:
        - name: lb-claim0
          persistentVolumeClaim:
            claimName: lb-claim0
status: {}
