apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /usr/local/bin/kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: service
  name: service
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /usr/local/bin/kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: service
    spec:
      hostNetwork: true
      containers:
        - image: 192.168.1.166:5000/app:1.3
          name: service
          resources: {}
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.43.0.10      
      restartPolicy: Always
status: {}
